In [2]:
# pip install faiss-cpu

In [3]:
# faiss==> facebook ai search similarity library
import numpy as np
import faiss

In [4]:
chunks = [
    {"id": "C0", "text": "EMI bounce Rs500",          "vec": [0.9, 0.8]},
    {"id": "C1", "text": "Interest rate 13%",         "vec": [0.7, 0.2]},
    {"id": "C2", "text": "Prepayment after 6 EMIs",   "vec": [0.6, 0.7]},
    {"id": "C3", "text": "Gold loan LTV 75%",         "vec": [0.2, 0.1]},
    {"id": "C4", "text": "Pre-closing penalty 4%",    "vec": [0.5, 0.9]},
    {"id": "C5", "text": "Credit score 700+",         "vec": [0.1, 0.8]},
    {"id": "C6", "text": "EMI due date 5th of month", "vec": [0.8, 0.6]},
    {"id": "C7", "text": "Foreclosure after 12 EMIs", "vec": [0.7, 0.8]},
]


In [8]:
vectors=np.array([c["vec"] for c in chunks],dtype="float32")

In [12]:
dimension = vectors.shape[1]

flat_l2 = faiss.IndexFlatL2(dimension)
flat_l2.add(vectors)

In [14]:
print("total vectors:", flat_l2.ntotal)
memory_bytes = flat_l2.ntotal * dimension * 4
print("memory usage (bytes):", memory_bytes)

total vectors: 8
memory usage (bytes): 64


In [15]:
query_vector = np.array([[0.8, 0.7]], dtype="float32")
D, I = flat_l2.search(query_vector, k=3)
D,I

(array([[0.00999999, 0.02      , 0.02000001]], dtype=float32),
 array([[6, 0, 7]]))

In [18]:
I[0]

array([6, 0, 7])

In [22]:
chunks[6]['text']

'EMI due date 5th of month'

In [16]:
for rank, idx in enumerate(I[0]):
    print(f"Rank {rank+1}: Chunk ID: {chunks[idx]['id']}, Text: {chunks[idx]['text']}, Distance: {D[0][rank]:.4f}")

Rank 1: Chunk ID: C6, Text: EMI due date 5th of month, Distance: 0.0100
Rank 2: Chunk ID: C0, Text: EMI bounce Rs500, Distance: 0.0200
Rank 3: Chunk ID: C7, Text: Foreclosure after 12 EMIs, Distance: 0.0200


In [24]:
dimension = vectors.shape[1]

flat_l2 = faiss.IndexFlatIP(dimension)
flat_l2.add(vectors)


query_vector = np.array([[0.8, 0.7]], dtype="float32")
D, I = flat_l2.search(query_vector, k=3)
D,I


(array([[1.28     , 1.12     , 1.0600001]], dtype=float32), array([[0, 7, 6]]))